# Generated by Django 4.2.4 on 2023-09-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followers',
            new_name='follower',
        ),
    ]
